In [1]:
import nbaPlayerStatModeling as nbaModel

In [ ]:
nba = nbaModel.playerStatModel(
        day_offset = 0, 
        season = '2024-25', 
        perMode = 'PerGame',
        num_simulations = 200000
)

In [5]:
nba.get_teams_playing()
nba.get_teams_data(
    base_url = 'https://stats.nba.com/stats/leaguedashteamstats?Conference=&DateFrom=&DateTo=&Division=&GameScope=&GameSegment=&Height=&ISTRound=&LastNGames=0&LeagueID=00&Location=&MeasureType={stattype}&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season={sid}&SeasonSegment=&SeasonType=Regular%20Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision='
)
nba.get_players_playing(
    url_base_nba_player_stat = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode={per}&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season={sid}&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID={tid}&TwoWay=0&VsConference=&VsDivision=&Weight=',
    minute_cutoff = 0
)
nba.get_props()

5  games today...
169 players returned from 10 teams, out of a total 10
745 prop bets for 76 players...


In [7]:
#nba.df_players = nba.df_players.iloc[1:10, :]
nba.get_player_home_adv(
    use_default=False
)

1 / 9 player splits..
2 / 9 player splits..
3 / 9 player splits..
4 / 9 player splits..
5 / 9 player splits..
6 / 9 player splits..
7 / 9 player splits..
8 / 9 player splits..
9 / 9 player splits..


In [140]:
#df_copy = nba.df_players.copy()
nba.df_players = df_copy.copy()


In [175]:
nba.df_players = df_copy.copy()

nba.model_expected_minutes()
nba.calculate_model_inputs()
#nba.df_players = nba.df_players.fillna(0)
nba.num_simulations = 100000
nba.model_stats()

In [178]:
len(nba.sim_fg3m[0])

100000

In [142]:
#nba.model_expected_pts()
#nba.model_expected_fg3m()


In [180]:
pts_cols = []
for i in nba.df_players.columns:
    if  'fg3m' in i.lower():
        pts_cols.append(i)

nba.df_players[pts_cols]

FG3M  FG3M_HOMEadj  FG3M_ROADadj   expFG3M  FG3MoProb  FG3MoOdds  \
0   3.2      1.200000      1.200000  3.890867    0.36568        173   
1   1.9      1.125000      1.111111  2.183712    0.54103       -117   
2   2.2      1.200000      1.200000  2.686276    0.31344        219   
3   3.2      1.052632      1.050000  3.440383    0.34943        186   
4   0.0           NaN           NaN  0.000000    1.00000  -99999999   
5   0.2      1.200000      1.200000  0.214755    1.00000  -99999999   
6   3.0      1.026667      1.025974  3.093764    0.27384        265   
7   2.9      0.800000      0.800000  2.317847    0.61190       -157   
8   2.5      1.200000      1.189815  2.967165    0.41757        139   

   FG3MoOdds_deci  
0           2.735  
1           1.848  
2           3.190  
3           2.862  
4           1.000  
5           1.000  
6           3.652  
7           1.634  
8           2.395

array([[16, 29, 28, 31, 25, 17, 30, 26, 28],
       [13,  6, 13,  9, 10, 11, 19,  7,  9],
       [10,  5,  9,  6,  9, 12, 11, 15, 10],
       [34, 19, 22, 18, 18, 24, 26, 21, 25],
       [ 4,  4,  5,  4,  7,  5,  4,  2,  2],
       [34, 34, 31, 25, 27, 33, 31, 28, 39],
       [ 8, 16,  7, 15, 12, 14, 13,  8,  7],
       [31, 27, 15, 10, 25, 23, 13, 21, 12],
       [16, 11, 17, 26, 16,  8, 17, 11, 13]])

In [105]:
player = 'Kenrich Williams'

In [106]:
nba.df_players[nba.df_players['PLAYER_NAME']!=player][['PLAYER_NAME', 'REB', 'expReb', 'reb_line', 'reb_oOdds', 'REBoOdds','REBoOdds_deci','REBoProb']]

PLAYER_NAME  REB    expReb  reb_line  reb_oOdds  REBoOdds  \
0      CJ McCollum  3.7  3.330953       3.5     -115.0       130   
1   Jordan Hawkins  2.4  2.095692       2.5      120.0       187   
2    Jose Alvarado  2.1  2.472305       2.5     -150.0       125   
3  Trey Murphy III  5.2  5.070224       5.5      105.0       148   
4       Yves Missi  8.0  8.036236       8.5     -120.0       142   
5  Zion Williamson  7.4  7.479165       6.5     -110.0      -161   
6    Klay Thompson  3.5  3.494745       4.5      110.0       263   
7     Kyrie Irving  4.8  5.410859       5.5     -114.0       121   
8     Max Christie  5.2  4.255215       5.5      105.0       279   

   REBoOdds_deci  REBoProb  
0          2.305    0.4338  
1          2.877    0.3476  
2          2.260    0.4425  
3          2.480    0.4032  
4          2.426    0.4122  
5          1.619    0.6177  
6          3.636    0.2750  
7          2.210    0.4524  
8          3.791    0.2638

In [32]:
nba.df_players[nba.df_players['PLAYER_NAME']==player][['PLAYER_NAME', 'AST', 'expAst', 'ast_line', 'ast_oOdds', 'ASToOdds','ASToOdds_deci','ASToProb']]

PLAYER_NAME  AST    expAst  ast_line  ast_oOdds  ASToOdds  \
65  Kenrich Williams  1.2  1.347933       1.5      115.0       157   

    ASToOdds_deci  ASToProb  
65           2.57  0.389085

In [173]:
nba.df_players[nba.df_players['PLAYER_NAME']!=player][['PLAYER_NAME', 'PTS', 'expPts', 'pts_line', 'pts_oOdds', 'PTSoOdds','PTSoOdds_deci','PTSoProb']]

PLAYER_NAME   PTS     expPts  pts_line  pts_oOdds  PTSoOdds  \
0      CJ McCollum  22.5  25.935139      23.5     -124.0      -147   
1   Jordan Hawkins  10.6  11.183786       9.5     -104.0      -195   
2    Jose Alvarado  10.0  12.198321      11.5     -125.0      -116   
3  Trey Murphy III  22.4  22.721885      24.5      105.0       184   
4       Yves Missi   8.5   7.303305       8.5     -124.0       276   
5  Zion Williamson  24.4  29.125603      24.5     -110.0      -345   
6    Klay Thompson  13.9  13.796205      16.5     -120.0       232   
7     Kyrie Irving  24.6  21.409743      27.5     -105.0       744   
8     Max Christie  17.3  17.528985      15.5     -110.0      -143   

   PTSoOdds_deci  PTSoProb  
0          1.677   0.59621  
1          1.510   0.66214  
2          1.855   0.53903  
3          2.844   0.35162  
4          3.764   0.26565  
5          1.289   0.77557  
6          3.328   0.30052  
7          8.446   0.11840  
8          1.697   0.58936

In [67]:
nba.df_players.to_excel('test.xlsx')

In [49]:
nba.df_players['expAst'].values

array([5.12279194, 4.98906653, 2.06787421, 8.85399571, 4.02008345])

In [46]:
np.random.poisson(nba.df_players['expAst'].values[:, None], (len(nba.df_players), 10000))

array([[ 1,  7,  8, ...,  6,  7,  4],
       [ 9,  4,  2, ...,  6,  6,  3],
       [ 3,  1,  2, ...,  1,  4,  3],
       [14,  8,  6, ..., 12,  5,  9],
       [ 5,  5,  5, ...,  6,  7,  5]])

In [50]:
(len(nba.df_players), 10000)

(5, 10000)

In [105]:
for i in nba.df_players.columns:
    if 'reb' in i.lower():
        print(i)

OREB
DREB
REB
OREB_PCT
DREB_PCT
OREBadj
DREBadj
reb_line
reb_oOdds
reb_uOdds
OREB_HOMEadj
DREB_HOMEadj
REB_HOMEadj
OREB_ROADadj
DREB_ROADadj
REB_ROADadj
expReb
REBoProb
REBoOdds
REBoOdds_deci


In [ ]:
from nba_api.stats.endpoints import PlayerDashboardByGeneralSplits

############### DF IDX 6 is days rest splits
a.get_data_frames()[6]

In [26]:
a.get_data_frames()[6]

GROUP_SET   GROUP_VALUE  GP   W   L  W_PCT          MIN  FGM  FGA  FG_PCT  \
0  Days Rest   0 Days Rest   9   4   5  0.444   303.761667   51  139   0.367   
1  Days Rest   1 Days Rest  28  12  16  0.429  1033.046667  210  512   0.410   
2  Days Rest   2 Days Rest   7   3   4  0.429   251.258333   51  118   0.432   
3  Days Rest   3 Days Rest   2   2   0  1.000    70.165000   18   38   0.474   
4  Days Rest   4 Days Rest   2   1   1  0.500    74.778333   20   47   0.426   
5  Days Rest   5 Days Rest   1   1   0  1.000    33.125000    5   18   0.278   
6  Days Rest  6+ Days Rest   1   1   0  1.000    36.678333    7   16   0.438   

   ...  BLK_RANK  BLKA_RANK  PF_RANK  PFD_RANK  PTS_RANK  PLUS_MINUS_RANK  \
0  ...         1          5        6         3         3                1   
1  ...         2          7        7         1         1                7   
2  ...         2          6        5         2         2                4   
3  ...         2          3        2         5         5                2   
4  ...         6          4        4         4         4                5   
5  ...         6          2        2         7         7                6   
6  ...         5          1        1         5         6                2   

   NBA_FANTASY_PTS_RANK  DD2_RANK  TD3_RANK  WNBA_FANTASY_PTS_RANK  
0                     2         2         1                      2  
1                     1         1         1                      1  
2                     3         3         1                      3  
3                     5         4         1                      5  
4                     4         4         1                      4  
5                     7         7         1                      7  
6                     6         4         1                      6  

[7 rows x 62 columns]